#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

# decrease swap use
mkdir -p /etc/sysctl.d
echo "vm.swappiness=10" | sudo tee /etc/sysctl.d/99-swappiness.conf >/dev/null

# configure keyboard and mouse
sudo mkdir -p /etc/X11/xorg.conf.d

sudo tee /etc/X11/xorg.conf.d/10-keyboard.conf >/dev/null <<EOF
Section "InputClass"
    Identifier "My Keyboard"
    MatchIsKeyboard "on"
    Option "XkbLayout" "us,ru"
    Option "XKbOptions" "grp:win_space_toggle,caps:ctrl_modifier"
EndSection
EOF

sudo tee /etc/X11/xorg.conf.d/20-mouse-acceleration.conf >/dev/null <<EOF
Section "InputClass"
    Identifier "My Mouse"
    Driver "libinput"
    MatchIsPointer "yes"
    Option "AccelProfile" "flat"
    Option "AccelSpeed" "0"
EndSection
EOF

# set Cloudflare DNS servers with DNS over TLS
sudo mkdir -p /etc/systemd/resolved.conf.d
sudo mkdir -p /etc/NetworkManager/conf.d

sudo tee /etc/systemd/resolved.conf.d/dns.conf >/dev/null <<EOF
[Resolve]
DNS=1.1.1.1#one.one.one.one 1.0.0.1#one.one.one.one 2606:4700:4700::1111#one.one.one.one 2606:4700:4700::1001#one.one.one.one
Domains=~.
DNSOverTLS=yes
EOF

sudo tee /etc/NetworkManager/conf.d/dns.conf >/dev/null <<EOF
[main]
dns=none
systemd-resolved=false
EOF

sudo systemctl daemon-reload
sudo systemctl restart systemd-resolved
sudo systemctl restart NetworkManager

sudo systemd-resolve --interface="$(ip -br l | awk '$1 !~ "lo|vir|wl" {print $1}' | grep enp)" --set-dns 1.1.1.1
systemd-resolve --flush-caches

# update the system
sudo pacman -Syu --noconfirm

# install packages
sudo pacman -Sy && sudo pacman -S --needed --noconfirm \
    pacman-contrib \
    xorg-server \
    xorg-xinit \
    xorg-xsetroot \
    libxft \
    libxinerama \
    timeshift \
    go \
    npm \
    fontconfig \
    hdparm \
    man-db \
    ufw \
    stow \
    fzf \
    ripgrep \
    fd \
    bat \
    poppler \
    ffmpegthumbnailer \
    mediainfo \
    imagemagick \
    ueberzug \
    feh \
    unzip \
    htop \
    ncdu \
    tmux \
    neovim \
    emacs \
    ranger \
    dunst \
    udiskie \
    picom \
    ly \
    wmname \
    xdotool \
    xclip \
    hsetroot \
    keepassxc \
    playerctl \
    mpv \
    flameshot \
    yt-dlp \
    transmission-cli \
    gtk-engine-murrine \
    xcursor-vanilla-dmz \
    papirus-icon-theme \
    telegram-desktop

# copy fonts
mkdir -p ~/.local/share/fonts
[[ -d ~/.dotfiles/fonts ]] && cp -r ~/.dotfiles/fonts/* ~/.local/share/fonts
fc-cache -fv

# enable drive cache for all HDDs
sudo mkdir -p /etc/udev/rules.d

echo "ACTION==\"add|change\", KERNEL==\"sd[a-z]\", ATTRS{queue/rotational}==\"1\", RUN+=\""$(which hdparm)" -W 1 /dev/%k\"" |
    sudo tee /etc/udev/rules.d/69-hdparm.rules >/dev/null

# enable firewall
sudo systemctl enable --now ufw
sudo ufw enable

# enable display manager
sudo systemctl enable ly

# configure transmission
sudo mkdir -p /etc/systemd/system/transmission-daemon.service.d
sudo tee /etc/systemd/system/transmission-daemon.service.d/username.conf >/dev/null <<EOF
[Service]
User=ryadovoy
EOF

# install yay
mkdir -p ~/source

if [[ ! -d ~/source/yay ]]; then
    git clone https://aur.archlinux.org/yay-bin.git ~/source/yay
    cd ~/source/yay && makepkg -si --noconfirm
fi

# install AUR packages
yay -Y --gendb
yay -Y --devel --save

yay -Sy && yay -S --needed --noconfirm \
    brave-bin \
    tmux-resurrect \
    betterlockscreen \
    spotify \
    pfetch

# install dwm, st and dmenu
if [[ ! -d ~/source/dwm ]]; then
    git clone https://github.com/ryadovoyy/dwm.git ~/source/dwm
    cd ~/source/dwm && sudo make install
fi

sudo mkdir -p /usr/share/xsessions
sudo tee /usr/share/xsessions/dwm.desktop >/dev/null <<EOF
[Desktop Entry]
Encoding=UTF-8
Name=Dwm
Comment=The dynamic window manager
Exec=dwm
Icon=dwm
Type=XSession
EOF

if [[ ! -d ~/source/st ]]; then
    git clone https://github.com/ryadovoyy/st.git ~/source/st
    cd ~/source/st && sudo make install
fi

if [[ ! -d ~/source/dmenu ]]; then
    git clone https://github.com/ryadovoyy/dmenu.git ~/source/dmenu
    cd ~/source/dmenu && sudo make install
fi

# install dotfiles
[[ -f ~/.dotfiles/install-dotfiles ]] && source ~/.dotfiles/install-dotfiles
