#!/usr/bin/env bash

set -euo pipefail
IFS=$'\n\t'

# decrease swap use
mkdir -p /etc/sysctl.d
echo "vm.swappiness=10" | sudo tee /etc/sysctl.d/99-swappiness.conf >/dev/null

# set Cloudflare DNS servers with DNS over TLS
sudo mkdir -p /etc/systemd/resolved.conf.d
sudo mkdir -p /etc/NetworkManager/conf.d

sudo tee /etc/systemd/resolved.conf.d/dns.conf >/dev/null <<EOF
[Resolve]
DNS=1.1.1.1#one.one.one.one 1.0.0.1#one.one.one.one 2606:4700:4700::1111#one.one.one.one 2606:4700:4700::1001#one.one.one.one
Domains=~.
DNSOverTLS=yes
EOF

sudo tee /etc/NetworkManager/conf.d/dns.conf >/dev/null <<EOF
[main]
dns=none
systemd-resolved=false
EOF

sudo systemctl daemon-reload
sudo systemctl restart systemd-resolved
sudo systemctl restart NetworkManager

sudo systemd-resolve --interface="$(ip -br l | awk '$1 !~ "lo|vir|wl" {print $1}' | grep enp)" --set-dns 1.1.1.1
systemd-resolve --flush-caches

# update the system
sudo pacman -Syu --noconfirm

# install packages
sudo pacman -Sy && sudo pacman -S --needed --noconfirm \
    # desktop environment
    sway \
    swaylock \
    swayidle \
    i3status \
    wmenu \
    ghostty \
    mako \
    flameshot \
    udiskie \
    wl-clipboard \
    xdg-desktop-portal-wlr \
    ly \
    # fonts
    fontconfig \
    noto-fonts \
    noto-fonts-extra \
    noto-fonts-cjk \
    noto-fonts-emoji \
    # main dev tools
    zellij \
    helix \
    lazygit \
    yazi \
    fzf \
    # utils
    ripgrep \
    fd \
    imagemagick \
    ffmpeg \
    poppler \
    playerctl \
    unzip \
    stow \
    pacman-contrib \
    # other programs
    mpv \
    imv \
    openssh \
    timeshift \
    man-db \
    ufw \
    htop \
    keepassxc \
    transmission-cli \
    telegram-desktop

# configure fonts
mkdir -p ~/.local/share/fonts
[[ -d ~/.dotfiles/fonts ]] && cp -r ~/.dotfiles/fonts/* ~/.local/share/fonts
[[ -f /etc/profile.d/freetype2.sh ]] && sudo sed -i '$s/^#//' /etc/profile.d/freetype2.sh
fc-cache -fv

# enable firewall
sudo systemctl enable --now ufw
sudo ufw enable

# enable display manager
sudo systemctl enable ly

# configure and enable transmission
sudo mkdir -p /etc/systemd/system/transmission-daemon.service.d
sudo tee /etc/systemd/system/transmission-daemon.service.d/username.conf >/dev/null <<EOF
[Service]
User=ryadovoy
EOF

sudo systemctl enable transmission.service

# install yay
mkdir -p ~/source

if [[ ! -d ~/source/yay ]]; then
    git clone https://aur.archlinux.org/yay-bin.git ~/source/yay
    cd ~/source/yay && makepkg -si --noconfirm
fi

# install AUR packages
yay -Y --gendb
yay -Y --devel --save

yay -Sy && yay -S --needed --noconfirm \
    brave-bin \
    spotify

# install dotfiles
[[ -f ~/.dotfiles/install-dotfiles ]] && source ~/.dotfiles/install-dotfiles
