#!/bin/sh

go install \
    golang.org/x/tools/gopls@latest \
    golang.org/x/tools/cmd/goimports@latest \
    github.com/go-delve/delve/cmd/dlv@latest \
    github.com/nametake/golangci-lint-langserver@latest \
    github.com/golangci/golangci-lint/v2/cmd/golangci-lint@latest
