require('nvim-treesitter.install').prefer_git = true

require('nvim-treesitter.configs').setup({
  highlight = { enable = true },
  indent = { enable = true },
  textobjects = {
    select = {
      enable = true,
      lookahead = true,
      keymaps = {
        ['af'] = '@function.outer',
        ['if'] = '@function.inner',
        ['ac'] = '@class.outer',
        ['ic'] = '@class.inner',
      },
    },
  },
  auto_install = true,
  ensure_installed = {
    'bash',
    'c',
    'cmake',
    'comment',
    'cpp',
    'diff',
    'dockerfile',
    'go',
    'gomod',
    'graphql',
    'html',
    'http',
    'java',
    'javascript',
    'json',
    'lua',
    'luadoc',
    'make',
    'markdown',
    'php',
    'phpdoc',
    'prisma',
    'python',
    'regex',
    'toml',
    'typescript',
    'vim',
    'vimdoc',
    'yaml',
  },
})
